function fg = fig_setting_default()

% figure style
fg.width = 3;     % Width in inches
fg.height = 3;    % Height in inches
fg.fsz = 20;      % Fontsize
fg.lw = 1;      % LineWidth
fg.msz = 15;       % MarkerSize
fg.linewidth = 2.5;  % line width

fg.pu = get(gcf,'PaperUnits');
fg.pp = get(gcf,'PaperPosition');
set(gcf,...
    'Units',fg.pu,...
    'Position',fg.pp,...
    'color', 'w'...
    );
set(gca,...
    'box','off',...
    'layer','top',...
    'TickDir','in',...
    'FontSize', fg.fsz,...
    'LineWidth', fg.linewidth...
    );
